corsAllowedOrigins: ["http://localhost:3000"]
redis:
  addrs:
    - "redis:6379"
eventsRedis:
  addrs:
    - "redis:6379"
eventsNats:
  Servers:
    - "nats://nats:4223"
  ClusterID: "test-cluster"
  Subject: "ArmadaTest"
  QueueGroup: "ArmadaEventRedisProcessor"
