name: CI

on: [push]

jobs:
  e2e:
    name: End-to-end tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Build
        run: make build-ci
      - name: Start cluster for e2e tests
        run: |
          docker-compose -p e2e up
          docker-compose -p e2e exec -T kubernetes sh -c "until curl -s -f http://localhost:10080/kubernetes-ready; do sleep 1; done"
        working-directory: e2e/setup
      - name: Run tests
        run: PATH=${PATH}:${PWD}/bin INTEGRATION_ENABLED=true go test -v ./e2e/test/... -count=1
      - name: Stop cluster
        if: always()
        run: docker-compose -p e2e stop
        working-directory: e2e/setup
      - name: Display cluster logs
        if: always()
        run: docker-compose -p e2e logs -t
        working-directory: e2e/setup
