name: CI

on: [push]

jobs:
  e2e:
    name: End-to-end tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Install Docker Compose v2
        run: |
          mkdir ~/.docker/cli-plugins
          curl -sL https://github.com/docker/compose-cli/releases/download/v2.0.0-beta.6/docker-compose-linux-amd64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose
      - name: Build
        run: make build-ci
      # - uses: engineerd/setup-kind@v0.5.0
      #   with:
      #     version: "v0.11.1"
      #     wait: "60s"
      # - name: Testing
      #   run: |
      #     kubectl cluster-info
      #     kubectl get pods -n kube-system
      #     echo "current-context:" $(kubectl config current-context)
      #     echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      # - name: Start cluster for e2e tests
      #   run: docker-compose -p e2e up --force-recreate -d
      #   working-directory: e2e/setup

      # - name: Wait for green status..
      #   run: |
      #     docker-compose -p e2e exec -T kubernetes sh -c "until curl -s -f http://kubernetes:10080/kubernetes-ready; do sleep 1; done"
      #   working-directory: e2e/setup
      # - name: Run tests
      #   run: |
      #     PATH=${PATH}:${PWD}/bin INTEGRATION_ENABLED=true go test -v ./e2e/test/... -count=1
      - name: Stop cluster
        if: always()
        run: docker-compose -p e2e down
        working-directory: e2e/setup
      - name: Display cluster logs
        if: always()
        run: docker-compose -p e2e logs -t
        working-directory: e2e/setup
